# Configurações globais e padrões do Chart
replicaCount: 1
appPort: 5000

image:
  repository: 142517507342.dkr.ecr.us-east-1.amazonaws.com/restapi-ecr
  pullPolicy: IfNotPresent
  # Overrides a tag padrão (appVersion no Chart.yaml)
  tag: "latest"

service:
  type: ClusterIP
  port: 80

# Variáveis de ambiente extras
env:
  FLASK_ENV: "development"
  FLASK_HOST: "0.0.0.0"

# Configurações do MongoDB
mongodb:
  secretName: mongodb-credentials
  db: restapi
  host: mongodb
  user: root

# Recursos (CPU/Memória) - Recomendado para Portfólio
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  host: api.restapi-flask.xyz
  # O ARN real obtido após o novo apply
  certificateArn: "arn:aws:acm:us-east-1:142517507342:certificate/19dc9f4e-07d3-48d1-a6fa-f1369a1ca84b"
 