apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restapi-flask
  name: restapi-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-flask
  template:
    metadata:
      labels:
        app: restapi-flask
    spec:
      containers:
      - image: restapi-flask:latest
        name: restapi-flask
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_HOST
          value: "0.0.0.0"
        - name: MONGODB_DB
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_DB
        - name: MONGODB_HOST
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_HOST
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
