name: CI/CD Pipeline - Deploy to Amazon EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: restapi-ecr
  EKS_CLUSTER: restapi-cluster

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Versão estável do Python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter and Tests
        run: make test

  deploy:
    name: Build and Deploy
    needs: test # Só roda se o job 'test' passar com sucesso
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/restapi-gh-actions-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.0'

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Deploy to EKS via Helm
        run: |
          helm upgrade --install restapi kubernetes/charts/restapi-flask \
            --set image.tag=${{ github.sha }} \
            --set ingress.certificateArn=arn:aws:acm:${{ env.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:certificate/19dc9f4e-07d3-48d1-a6fa-f1369a1ca84b
